// RTK Query API Index - Central export for all API hooks
export * from './baseApi';
export * from './rootApi';
export * from './lightcastApi';
export * from './jobPostingsApi';

// Re-export the main API slice
export { baseApi as api } from './baseApi';

// Import all hooks for convenience re-export
// import {
//   useHealthCheckQuery,
//   useLoginMutation,
//   useLogoutMutation,
//   useRefreshTokenMutation,
//   useGetCurrentUserQuery,
//   useGetUserProfileQuery,
//   useUpdateUserProfileMutation,
//   useDeleteUserProfileMutation,
//   useGetCompaniesQuery,
//   useLazyGetCompaniesQuery,
//   useGetCompanyByIdQuery,
//   useCreateCompanyMutation,
//   useUpdateCompanyMutation,
//   useDeleteCompanyMutation,
//   useUpdateUserCompanyMutation,
// } from './rootApi';

// import {
//   useGetLightcastRootQuery,
//   useGetLightcastTokenQuery,
//   useGetJobPostingsQuery,
//   useLazyGetJobPostingsQuery,
//   useGetSkillsQuery,
//   useLazyGetSkillsQuery,
//   useGetSkillByIdQuery,
//   useSearchSkillsQuery,
//   useLazySearchSkillsQuery,
//   useGetTrendingSkillsQuery,
//   useGetOccupationsQuery,
//   useLazyGetOccupationsQuery,
//   useGetOccupationByIdQuery,
//   useSearchOccupationsQuery,
//   useLazySearchOccupationsQuery,
//   useGetSkillsByOccupationQuery,
//   useGetLaborMarketDataQuery,
//   useLazyGetLaborMarketDataQuery,
//   useGetEducationProgramsQuery,
//   useLazyGetEducationProgramsQuery,
//   useGetSkillsGapAnalysisQuery,
//   useLazyGetSkillsGapAnalysisQuery,
// } from './lightcastApi';

// import {
//   useGetJobsQuery,
//   useLazyGetJobsQuery,
//   useGetJobByIdQuery,
//   useCreateJobMutation,
//   useUpdateJobMutation,
//   useDeleteJobMutation,
//   useSearchJobsQuery,
//   useLazySearchJobsQuery,
//   useGetJobsByCompanyQuery,
//   useLazyGetJobsByCompanyQuery,
//   useGetJobsByLocationQuery,
//   useLazyGetJobsByLocationQuery,
//   useGetJobsBySkillQuery,
//   useLazyGetJobsBySkillQuery,
//   useGetJobsBySalaryRangeQuery,
//   useLazyGetJobsBySalaryRangeQuery,
//   useGetJobCategoriesQuery,
//   useGetJobsByCategoryQuery,
//   useLazyGetJobsByCategoryQuery,
//   useGetJobStatsQuery,
//   useLazyGetJobStatsQuery,
//   useGetTrendingJobsQuery,
//   useLazyGetTrendingJobsQuery,
//   useGetMarketInsightsQuery,
//   useLazyGetMarketInsightsQuery,
//   useGetSkillsDemandQuery,
//   useLazyGetSkillsDemandQuery,
//   useCreateJobAlertMutation,
//   useGetUserJobAlertsQuery,
//   useUpdateJobAlertMutation,
//   useDeleteJobAlertMutation,
//   useSubmitJobApplicationMutation,
//   useGetUserJobApplicationsQuery,
//   useGetJobApplicationByIdQuery,
//   useUpdateJobApplicationStatusMutation,
// } from './jobPostingsApi';

// Export combined hooks object for convenience
// export const apiHooks = {
  // Root API hooks
  useHealthCheckQuery,
  useLoginMutation,
  useLogoutMutation,
  useRefreshTokenMutation,
  useGetCurrentUserQuery,
  useGetUserProfileQuery,
  useUpdateUserProfileMutation,
  useDeleteUserProfileMutation,
  useGetCompaniesQuery,
  useLazyGetCompaniesQuery,
  useGetCompanyByIdQuery,
  useCreateCompanyMutation,
  useUpdateCompanyMutation,
  useDeleteCompanyMutation,
  useUpdateUserCompanyMutation,

  // Lightcast API hooks
  useGetLightcastRootQuery,
  useGetLightcastTokenQuery,
  useGetJobPostingsQuery,
  useLazyGetJobPostingsQuery,
  useGetSkillsQuery,
  useLazyGetSkillsQuery,
  useGetSkillByIdQuery,
  useSearchSkillsQuery,
  useLazySearchSkillsQuery,
  useGetTrendingSkillsQuery,
  useGetOccupationsQuery,
  useLazyGetOccupationsQuery,
  useGetOccupationByIdQuery,
  useSearchOccupationsQuery,
  useLazySearchOccupationsQuery,
  useGetSkillsByOccupationQuery,
  useGetLaborMarketDataQuery,
  useLazyGetLaborMarketDataQuery,
  useGetEducationProgramsQuery,
  useLazyGetEducationProgramsQuery,
  useGetSkillsGapAnalysisQuery,
  useLazyGetSkillsGapAnalysisQuery,

  // Job Postings API hooks
  useGetJobsQuery,
  useLazyGetJobsQuery,
  useGetJobByIdQuery,
  useCreateJobMutation,
  useUpdateJobMutation,
  useDeleteJobMutation,
  useSearchJobsQuery,
  useLazySearchJobsQuery,
  useGetJobsByCompanyQuery,
  useLazyGetJobsByCompanyQuery,
  useGetJobsByLocationQuery,
  useLazyGetJobsByLocationQuery,
  useGetJobsBySkillQuery,
  useLazyGetJobsBySkillQuery,
  useGetJobsBySalaryRangeQuery,
  useLazyGetJobsBySalaryRangeQuery,
  useGetJobCategoriesQuery,
  useGetJobsByCategoryQuery,
  useLazyGetJobsByCategoryQuery,
  useGetJobStatsQuery,
  useLazyGetJobStatsQuery,
  useGetTrendingJobsQuery,
  useLazyGetTrendingJobsQuery,
  useGetMarketInsightsQuery,
  useLazyGetMarketInsightsQuery,
  useGetSkillsDemandQuery,
  useLazyGetSkillsDemandQuery,
  useCreateJobAlertMutation,
  useGetUserJobAlertsQuery,
  useUpdateJobAlertMutation,
  useDeleteJobAlertMutation,
  useSubmitJobApplicationMutation,
  useGetUserJobApplicationsQuery,
  useGetJobApplicationByIdQuery,
  useUpdateJobApplicationStatusMutation,
};
